name: Create Coverage

on: 
  push:
    branches:
    - main

jobs:
  generate-coverage-report:
    uses: eclipse-kanto/kanto/.github/workflows/coverage-template.yaml
    with: 
      coverage-command: go test ./... -coverprofile=coverage.out
